### ISSUE TITLE
Homepage - Dead links (error 404) on each item of Featured Apps section

### ISSUE THREAD

**Issue by i-give-up** [mltframework/mlt_web#2]
It seems like the link icon on each of the Featured Apps lead to a 404 error page. Please see the screenshot below

![mlt_homepage_dead_links](https://user-images.githubusercontent.com/14156307/37150607-4b02c2f8-230d-11e8-9fbe-a9ee7a258b62.png)

**Comment by ddennedy** [comment]
Thanks. Fixed in commit 06f31d877a59c044ffe92921a122f1b9e0d395ca
